- name: Update Jenkins IP in Route53
  hosts: localhost
  tasks:
   - name: Update Jenkins IP
     amazon.aws.route53:
       state: present
       zone: kdevopsb26.online
       record: jenkins.kdevopsb26.online
       type: A
       ttl: 10
       value: 3.94.208.122
       wait: true


